version: 2

jobs:
  build:
    docker:
      - image: massgov/drupal-container:1.0.5-ci
    working_directory: ~/dtt
    environment:
      - DTT_BASE_URL=http://localhost
      - APACHE_DOCROOT=~/dtt/web
    steps:
      - checkout
      - restore_cache: # special step to restore the dependency cache if `composer.lock` does not change
          keys:
            - composer-v1-{{ checksum "composer.lock" }}
            - composer-v1-
      - run: composer install -n --prefer-dist
      - save_cache: # special step to save the dependency cache with the `composer.lock` cache key template
          key: composer-v1-{{ checksum "composer.lock" }}
          paths:
            - vendor
            - web
      - run: drush si -yv --db-url=sqlite://sites/default/files/.ht.sqlite standard
      - run: phpunit ./ExampleTestCase.php