version: 2

jobs:
  build:
    working_directory: /var/www/code
    docker:
      # @see https://github.com/massgov/Drupal-Container
      - image: massgov/drupal-container:1.0.2-ci
        environment:
          COMPOSER_ALLOW_SUPERUSER: 1
          DTT_BASE_URL: http://dtt.local
          APACHE_DOCROOT: /var/www/code/web
    steps:
      - checkout
      - run: echo 'export PATH=/var/www/code/vendor/bin:$PATH' >> $BASH_ENV
      - restore_cache: # special step to restore the dependency cache if `composer.lock` does not change
          keys:
            - composer-v1-{{ checksum "composer.lock" }}
            - composer-v1-
      - run: composer install -n --prefer-dist
      - save_cache: # special step to save the dependency cache with the `composer.lock` cache key template
          key: composer-v1-{{ checksum "composer.lock" }}
          paths:
            - vendor
            - web
      - run: {name: 'Start Apache', command: '/usr/local/bin/apache2-foreground-enhanced', background: true}
      - run: drush si -yv --db-url=sqlite://sites/default/files/.ht.sqlite standard
      - run: phpunit ./ExampleTestCase.php